version: '3.9'
services:

  flask_app:
    build: ./app
    container_name: flask_app
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bewise_db
      POSTGRES_HOST: db_postgres
      DATABASE_PORT: 5432
    depends_on:
      - db_postgres
    restart: on-failure
    volumes:
      - ./app:/app
    ports:
      - '5000:5000'
    networks:
        - backend
  db_postgres:
    image: postgres:13.7-alpine3.16
    networks:
      - backend
    container_name: db_postgres
    ports:
        - "5433:5432"
    volumes:
        - ./db_postgres:/var/lib/postgresql/data

    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bewise_db


networks:
  backend:
    name: backend
